    - name: install php
      action: apt name={{ item }} state=installed
      with_items:
          - php5-fpm
          - php-apc
          - php-pear
          - php5-curl
          - php5-intl
      notify:
        - restart php5-fpm

    - name: install apc.ini template
      action: template src=apc.ini dest=/etc/php5/conf.d/apc.ini
      notify:
        - restart php5-fpm

    - name: remove php5-fpm default pool
      action: file path=/etc/php5/fpm/pool.d/www.conf state=absent
      notify:
        - restart php5-fpm